# Use Python
language: python

# Install the test runner.
install: pip install tox

# Run each environment separately so we get errors back from all of them.
matrix:
  include:
    - python: 3.4
      env: TOX_ENV=py34
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=py36
script:
  - tox -e $TOX_ENV

# Control the branches that get built.
branches:
  only:
    - master
